# ansible/inventory/group_vars/panda-dev.yml

# Where we store the versions
versions_file: "../sites_manifests/panda-dev-versions.yml"

# If you still want to toggle roles here, keep them:
enable_apt_install: true
enable_network_setup: true
enable_docker_load: true
enable_helm_install: false
enable_netplan_config: false


configurations:
  # PROXMOX CONNECTION PARAMS #
  system_type: 'dev'
  proxmox_host_ip: "10.50.0.24"
  proxmox_user: "root@pam"
  proxmox_user_password: "Pa$$w0rd!"
  proxmox_node: "vm1"
  installation_mode: offline  # or online

  # vms configuration #
  vms:
    workernode-panda:
      name: "worker-node-panda"
      ip: "10.50.0.152"
      vmid: 106
      dev: true
      type: workernode
      gpu: true

    masternode-panda:
      name: "masternode-panda"
      ip: "10.50.0.151"
      vmid: 107
      dev: true
      type: workernode
      gpu: false
  # # vms configuration #

  # machines:
  #   interrogator:
  #     # PROXMOX CONNECTION PARAMS #
  #     system_type: 'prod'
  #     proxmox_host_ip: "10.50.2.101"
  #     proxmox_user: "root@pam"
  #     proxmpx_user_password: "PASSW0RD"
  #     installation_mode: offline  # or online
  #     # PROXMOX CONNECTION PARAMS #
