{{- $offlineDeploy := (env "OFFLINE_DEPLOY" | default "offline_deploy") -}}
{{- $thirdSubnetOctet := (env "THIRD_SUBNET_OCTET" | default "10") -}}
{{- $secondSubnetOctet := (env "SECOND_SUBNET_OCTET" | default "10") -}}

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/kube-prometheus-stack
    values:
      - prometheus-stack/values.yaml

  - name: telegraf
    namespace: monitoring
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/telegraf
    values:
      - telegraf/values.yaml
      # - telegraf/{{ env "PROJECT_NAME" | default "default_project" }}/values.yml

  - name: helm-dashboard
    namespace: kube-system
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/helm-dashboard
    values:
      - helm-dashboard/values.yaml
      - service:
          loadBalancerIP: 10.{{ $secondSubnetOctet }}.{{ $thirdSubnetOctet }}.106

  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: /home/prisma/{{ $offlineDeploy }}/helm_charts/downloaded_helm_charts/kubernetes-dashboard
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "kubernetes-dashboard/auth.yaml"]  
    values:
      - kubernetes-dashboard/values.yaml
      - kong:
          proxy:
            LoadBalancerIP: 10.{{ $secondSubnetOctet }}.{{ $thirdSubnetOctet }}.107
